# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "account_allocations", :force => true do |t|
    t.column "account_id",     :integer
    t.column "amount",         :float
    t.column "created_by",     :integer
    t.column "updated_by",     :integer
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "allocable_id",   :integer
    t.column "allocable_type", :string,   :limit => 50
  end

  create_table "account_field_types", :force => true do |t|
    t.column "created_by",       :integer
    t.column "created_at",       :datetime
    t.column "updated_by",       :integer
    t.column "updated_at",       :datetime
    t.column "name",             :string,   :limit => 50
    t.column "code",             :string,   :limit => 6
    t.column "validation_regex", :string
  end

  create_table "account_types", :force => true do |t|
    t.column "created_by",               :integer
    t.column "created_at",               :datetime
    t.column "updated_by",               :integer
    t.column "updated_at",               :datetime
    t.column "name",                     :string,   :limit => 50
    t.column "segment_1_field_type_id",  :integer
    t.column "segment_2_field_type_id",  :integer
    t.column "segment_3_field_type_id",  :integer
    t.column "segment_4_field_type_id",  :integer
    t.column "segment_5_field_type_id",  :integer
    t.column "segment_6_field_type_id",  :integer
    t.column "segment_7_field_type_id",  :integer
    t.column "segment_8_field_type_id",  :integer
    t.column "segment_9_field_type_id",  :integer
    t.column "segment_10_field_type_id", :integer
    t.column "segment_11_field_type_id", :integer
    t.column "segment_12_field_type_id", :integer
    t.column "segment_13_field_type_id", :integer
    t.column "segment_14_field_type_id", :integer
    t.column "segment_15_field_type_id", :integer
    t.column "segment_16_field_type_id", :integer
    t.column "segment_17_field_type_id", :integer
    t.column "segment_18_field_type_id", :integer
    t.column "segment_19_field_type_id", :integer
    t.column "segment_20_field_type_id", :integer
    t.column "currency_id",              :integer
    t.column "primary_contact_id",       :integer
    t.column "primary_address_id",       :integer
    t.column "po_terms",                 :text
  end

  create_table "accounts", :force => true do |t|
    t.column "name",            :string,   :limit => 100
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "account_type_id", :integer
    t.column "segment_1",       :string,   :limit => 40
    t.column "segment_2",       :string,   :limit => 40
    t.column "segment_3",       :string,   :limit => 40
    t.column "segment_4",       :string,   :limit => 40
    t.column "segment_5",       :string,   :limit => 40
    t.column "segment_6",       :string,   :limit => 40
    t.column "segment_7",       :string,   :limit => 40
    t.column "segment_8",       :string,   :limit => 40
    t.column "segment_9",       :string,   :limit => 40
    t.column "segment_10",      :string,   :limit => 40
    t.column "segment_11",      :string,   :limit => 40
    t.column "segment_12",      :string,   :limit => 40
    t.column "segment_13",      :string,   :limit => 40
    t.column "segment_14",      :string,   :limit => 40
    t.column "segment_15",      :string,   :limit => 40
    t.column "segment_16",      :string,   :limit => 40
    t.column "segment_17",      :string,   :limit => 40
    t.column "segment_18",      :string,   :limit => 40
    t.column "segment_19",      :string,   :limit => 40
    t.column "segment_20",      :string,   :limit => 40
  end

  create_table "address_assignments", :force => true do |t|
    t.column "addressable_id",   :integer
    t.column "addressable_type", :string,  :limit => 50
    t.column "address_type_id",  :integer
    t.column "address_id",       :integer
  end

  create_table "addresses", :force => true do |t|
    t.column "name",               :string,   :limit => 50
    t.column "street1",            :string,   :limit => 100
    t.column "street2",            :string,   :limit => 100
    t.column "city",               :string,   :limit => 50
    t.column "state",              :string,   :limit => 50
    t.column "postal_code",        :string,   :limit => 50
    t.column "country_id",         :integer
    t.column "created_by",         :integer
    t.column "updated_by",         :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "address_owner_id",   :integer
    t.column "address_owner_type", :string,   :limit => 100
    t.column "attention",          :string
  end

  create_table "approval_limits", :force => true do |t|
    t.column "amount",      :decimal, :precision => 30, :scale => 2
    t.column "currency_id", :integer
  end

  create_table "approvals", :force => true do |t|
    t.column "parent_id",       :integer
    t.column "user_id",         :integer
    t.column "status",          :string,   :limit => 50
    t.column "approval_date",   :datetime
    t.column "note",            :text
    t.column "approval_key",    :string,   :limit => 100
    t.column "approvable_id",   :integer
    t.column "approvable_type", :string
  end

  create_table "ask_answers", :force => true do |t|
    t.column "ask_question_id", :integer
    t.column "text",            :text
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_categories", :force => true do |t|
    t.column "name",       :string,   :limit => 50
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "private",    :boolean,                :default => false
  end

  create_table "ask_moderators", :force => true do |t|
    t.column "ask_category_id", :integer
    t.column "user_id",         :integer
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_questions", :force => true do |t|
    t.column "text",            :text
    t.column "ask_category_id", :string,   :limit => 50
    t.column "status",          :string,   :limit => 50
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "ask_subscriptions", :force => true do |t|
    t.column "ask_category_id",     :integer
    t.column "subscriber_id",       :integer
    t.column "created_by",          :integer
    t.column "updated_by",          :integer
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "email_notifications", :boolean,  :default => false
  end

  create_table "asset_tags", :force => true do |t|
    t.column "order_line_id", :integer
    t.column "tag",           :string
    t.column "created_at",    :datetime
    t.column "created_by",    :integer
    t.column "updated_at",    :datetime
    t.column "updated_by",    :integer
    t.column "received",      :boolean,  :default => false
  end

  create_table "attachment_links", :force => true do |t|
    t.column "attachable_id",   :integer
    t.column "attachable_type", :string,   :limit => 50
    t.column "attachment_id",   :integer
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "intent",          :string,   :limit => 50
  end

  create_table "attachments", :force => true do |t|
    t.column "file",       :string,   :default => "", :null => false
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "type",       :string
    t.column "url",        :string
    t.column "text",       :text
  end

  create_table "budgets", :force => true do |t|
    t.column "department_id", :integer
    t.column "period_id",     :integer
    t.column "amount",        :float
    t.column "remaining",     :float
    t.column "created_by",    :integer
    t.column "updated_by",    :integer
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "catalog_items", :force => true do |t|
    t.column "catalog_header_id",      :integer,                                               :default => 0,   :null => false
    t.column "name",                   :string,                                                :default => "",  :null => false
    t.column "description",            :text
    t.column "uom_id",                 :integer,                                               :default => 0,   :null => false
    t.column "list_price",             :decimal,                :precision => 30, :scale => 2
    t.column "image",                  :string
    t.column "product_reviews_count",  :integer,                                               :default => 0,   :null => false
    t.column "avg_rating",             :float,                                                 :default => 0.0, :null => false
    t.column "created_by",             :integer
    t.column "updated_by",             :integer
    t.column "created_at",             :datetime
    t.column "updated_at",             :datetime
    t.column "source_part_num",        :string,   :limit => 50
    t.column "cached_at",              :datetime
    t.column "form_id",                :integer
    t.column "contract_id",            :integer
    t.column "list_price_currency_id", :integer
    t.column "lead_time",              :integer
  end

  add_index "catalog_items", ["name"], :name => "catalog_items_name_index"
  add_index "catalog_items", ["source_part_num"], :name => "catalog_items_spn_index"

  create_table "contacts", :force => true do |t|
    t.column "email",           :string,   :limit => 60
    t.column "phone_work",      :string,   :limit => 50
    t.column "photo",           :string
    t.column "notes",           :text
    t.column "created_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_by",      :integer
    t.column "updated_at",      :datetime
    t.column "phone_mobile",    :string,   :limit => 50
    t.column "name_prefix",     :string,   :limit => 10
    t.column "name_suffix",     :string,   :limit => 10
    t.column "name_additional", :string,   :limit => 50
    t.column "name_given",      :string,   :limit => 40
    t.column "name_family",     :string,   :limit => 40
    t.column "name_fullname",   :string,   :limit => 155
  end

  create_table "contracts", :force => true do |t|
    t.column "name",               :string,   :limit => 100
    t.column "number",             :string,   :limit => 50
    t.column "version",            :integer
    t.column "supplier_id",        :integer
    t.column "start_date",         :datetime
    t.column "end_date",           :datetime
    t.column "status",             :string,   :limit => 50
    t.column "minimum_value",      :float
    t.column "maximum_value",      :float
    t.column "created_by",         :integer
    t.column "updated_by",         :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "currency_id",        :integer
    t.column "terms",              :text
    t.column "bill_to_address_id", :integer
    t.column "legal_agreement",    :string
    t.column "catalog",            :string
    t.column "preferred_flag",     :boolean
  end

  create_table "countries", :force => true do |t|
    t.column "code",     :string,  :limit => 4
    t.column "name",     :string,  :limit => 100
    t.column "position", :integer
  end

  create_table "currencies", :force => true do |t|
    t.column "code",                 :string,  :limit => 6,   :default => "", :null => false
    t.column "name",                 :string,  :limit => 100, :default => "", :null => false
    t.column "min_accountable_unit", :float
    t.column "symbol",               :string,  :limit => 1
    t.column "enabled_flag",         :boolean
  end

  add_index "currencies", ["code"], :name => "currencies_code_index", :unique => true

  create_table "data_sources", :force => true do |t|
    t.column "file",         :string
    t.column "created_by",   :integer
    t.column "created_at",   :datetime
    t.column "updated_by",   :integer
    t.column "updated_at",   :datetime
    t.column "type",         :string,   :limit => 50
    t.column "source_for",   :string,   :limit => 50
    t.column "status",       :string,   :limit => 50
    t.column "job_key",      :string,   :limit => 50
    t.column "lock_version", :integer,                :default => 0, :null => false
    t.column "owner_type",   :string,   :limit => 50
    t.column "owner_id",     :integer
    t.column "error_text",   :text
    t.column "parameters",   :text
  end

  create_table "engine_schema_info", :id => false, :force => true do |t|
    t.column "engine_name", :string
    t.column "version",     :integer
  end

  create_table "exchange_rates", :force => true do |t|
    t.column "from_currency_id", :integer
    t.column "to_currency_id",   :integer
    t.column "rate",             :float
    t.column "rate_date",        :datetime
    t.column "created_by",       :integer
    t.column "created_at",       :datetime
    t.column "updated_by",       :integer
    t.column "updated_at",       :datetime
  end

  create_table "feeds", :force => true do |t|
    t.column "name",            :string,   :limit => 100
    t.column "url",             :string
    t.column "cache",           :text
    t.column "cache_data_type", :string,   :limit => 50
    t.column "last_cached_at",  :datetime
    t.column "expires_at",      :datetime
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "last_checked_at", :datetime
  end

  create_table "form_responses", :force => true do |t|
    t.column "response",   :text
    t.column "status",     :string,   :limit => 50
    t.column "created_by", :integer
    t.column "created_at", :datetime
    t.column "updated_by", :integer
    t.column "updated_at", :datetime
    t.column "form_id",    :integer
  end

  create_table "forms", :force => true do |t|
    t.column "name",        :string,   :limit => 100
    t.column "created_by",  :integer
    t.column "updated_by",  :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "description", :string
    t.column "status",      :string,   :limit => 50
  end

  create_table "invoice_headers", :force => true do |t|
    t.column "status",              :string,   :limit => 50
    t.column "supplier_id",         :integer
    t.column "remit_to_address_id", :integer
    t.column "invoice_number",      :string,   :limit => 40
    t.column "invoice_date",        :datetime
    t.column "terms_id",            :integer
    t.column "supplier_note",       :text
    t.column "internal_note",       :text
    t.column "image_scan",          :string
    t.column "shipping_amount",     :decimal,                :precision => 30, :scale => 2
    t.column "handling_amount",     :decimal,                :precision => 30, :scale => 2
    t.column "tax_amount",          :decimal,                :precision => 30, :scale => 2
    t.column "misc_amount",         :decimal,                :precision => 30, :scale => 2
    t.column "currency_id",         :integer
    t.column "created_by",          :integer
    t.column "updated_by",          :integer
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
  end

  create_table "invoice_lines", :force => true do |t|
    t.column "invoice_header_id",            :integer
    t.column "line_num",                     :integer
    t.column "type",                         :string,   :limit => 100
    t.column "description",                  :string
    t.column "catalog_item_id",              :integer
    t.column "uom_id",                       :integer
    t.column "quantity",                     :float
    t.column "price",                        :decimal,                 :precision => 30, :scale => 2
    t.column "total",                        :decimal,                 :precision => 30, :scale => 2
    t.column "currency_id",                  :integer
    t.column "accounting_total",             :decimal,                 :precision => 30, :scale => 2
    t.column "accounting_total_currency_id", :integer
    t.column "account_id",                   :integer
    t.column "created_by",                   :integer
    t.column "updated_by",                   :integer
    t.column "created_at",                   :datetime
    t.column "updated_at",                   :datetime
    t.column "status",                       :string
    t.column "order_line_id",                :integer
  end

  create_table "languages", :force => true do |t|
    t.column "code", :string, :limit => 12,  :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  create_table "notifications", :force => true do |t|
    t.column "body",          :text
    t.column "read_flag",     :boolean
    t.column "created_by",    :integer
    t.column "created_at",    :datetime
    t.column "updated_by",    :integer
    t.column "updated_at",    :datetime
    t.column "user_id",       :integer
    t.column "type",          :string,   :limit => 50
    t.column "status",        :string,   :limit => 50
    t.column "subject",       :string,   :limit => 100
    t.column "notifier_id",   :integer
    t.column "notifier_type", :string,   :limit => 50
  end

  create_table "objections", :force => true do |t|
    t.column "product_review_id", :integer
    t.column "status",            :string,   :limit => 20
    t.column "created_by",        :integer
    t.column "created_at",        :datetime
    t.column "updated_by",        :integer
    t.column "updated_at",        :datetime
    t.column "deleted_at",        :datetime
  end

  create_table "order_event_history", :force => true do |t|
    t.column "order_header_id", :integer
    t.column "status",          :string,   :limit => 50
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "order_header_versions", :force => true do |t|
    t.column "order_header_id",    :integer
    t.column "version",            :integer
    t.column "supplier_id",        :integer,                :default => 0
    t.column "status",             :string,   :limit => 50
    t.column "created_by",         :integer
    t.column "updated_by",         :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "ship_to_address_id", :integer
    t.column "ship_to_user_id",    :integer
    t.column "supplier_view_key",  :string
  end

  create_table "order_headers", :force => true do |t|
    t.column "supplier_id",        :integer,                :default => 0, :null => false
    t.column "status",             :string,   :limit => 50
    t.column "created_by",         :integer
    t.column "updated_by",         :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "ship_to_address_id", :integer
    t.column "ship_to_user_id",    :integer
    t.column "supplier_view_key",  :string
    t.column "acknowledged_flag",  :boolean
    t.column "version",            :integer
    t.column "pcard_id",           :integer
  end

  create_table "order_line_versions", :force => true do |t|
    t.column "order_line_id",                :integer
    t.column "version",                      :integer
    t.column "order_header_id",              :integer,                                                :default => 0
    t.column "item_id",                      :integer
    t.column "price",                        :decimal,                 :precision => 30, :scale => 2
    t.column "quantity",                     :float
    t.column "uom_id",                       :integer
    t.column "line_num",                     :integer
    t.column "created_by",                   :integer
    t.column "updated_by",                   :integer
    t.column "created_at",                   :datetime
    t.column "updated_at",                   :datetime
    t.column "contract_id",                  :integer
    t.column "form_response_id",             :integer
    t.column "total",                        :decimal,                 :precision => 30, :scale => 2
    t.column "description",                  :string
    t.column "supplier_id",                  :integer
    t.column "received",                     :float
    t.column "account_id",                   :integer
    t.column "status",                       :string,   :limit => 50
    t.column "currency_id",                  :integer
    t.column "accounting_total",             :decimal,                 :precision => 30, :scale => 2
    t.column "accounting_total_currency_id", :integer
    t.column "versioned_type",               :string,   :limit => 100
    t.column "order_header_version_id",      :integer
  end

  create_table "order_lines", :force => true do |t|
    t.column "order_header_id",              :integer,                                                :default => 0, :null => false
    t.column "item_id",                      :integer
    t.column "price",                        :decimal,                 :precision => 30, :scale => 2
    t.column "quantity",                     :float
    t.column "uom_id",                       :integer
    t.column "line_num",                     :integer
    t.column "created_by",                   :integer
    t.column "updated_by",                   :integer
    t.column "created_at",                   :datetime
    t.column "updated_at",                   :datetime
    t.column "contract_id",                  :integer
    t.column "form_response_id",             :integer
    t.column "total",                        :decimal,                 :precision => 30, :scale => 2
    t.column "description",                  :string
    t.column "supplier_id",                  :integer
    t.column "type",                         :string,   :limit => 100
    t.column "received",                     :float
    t.column "account_id",                   :integer
    t.column "status",                       :string,   :limit => 50
    t.column "currency_id",                  :integer
    t.column "accounting_total",             :decimal,                 :precision => 30, :scale => 2
    t.column "accounting_total_currency_id", :integer
    t.column "version",                      :integer
    t.column "need_by_date",                 :datetime
    t.column "source_part_num",              :string
  end

  create_table "organizations", :force => true do |t|
    t.column "parent_id",  :integer
    t.column "code",       :string,   :limit => 12,  :default => "", :null => false
    t.column "name",       :string,   :limit => 100, :default => "", :null => false
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "organizations_users", :id => false, :force => true do |t|
    t.column "organization_id", :integer
    t.column "user_id",         :integer
  end

  create_table "pcards", :force => true do |t|
    t.column "name",   :string
    t.column "number", :string
    t.column "expiry", :string
  end

  create_table "periods", :force => true do |t|
    t.column "start_date", :datetime
    t.column "end_date",   :datetime
    t.column "is_open",    :boolean
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "permissions", :force => true do |t|
    t.column "controller",  :string, :default => "", :null => false
    t.column "action",      :string, :default => "", :null => false
    t.column "description", :string
  end

  create_table "permissions_roles", :id => false, :force => true do |t|
    t.column "permission_id", :integer, :default => 0, :null => false
    t.column "role_id",       :integer, :default => 0, :null => false
  end

  create_table "policies", :force => true do |t|
    t.column "category_id", :integer
    t.column "name",        :string,   :limit => 100
    t.column "text",        :text
    t.column "created_by",  :integer
    t.column "updated_by",  :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "product_reviews", :force => true do |t|
    t.column "catalog_item_id", :integer,                 :default => 0, :null => false
    t.column "rating",          :integer,                 :default => 0, :null => false
    t.column "title",           :string,   :limit => 100
    t.column "text",            :text
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "source_id",       :integer,                 :default => 0, :null => false
    t.column "reviewer",        :string,   :limit => 100
    t.column "reviewed_at",     :datetime
    t.column "deleted_at",      :datetime
  end

  create_table "projects", :force => true do |t|
    t.column "name",       :string,   :limit => 100
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "punchin_sessions", :force => true do |t|
    t.column "user_id",      :integer
    t.column "buyer_cookie", :string
    t.column "checkout_url", :string
    t.column "start_page",   :string
    t.column "created_by",   :integer
    t.column "created_at",   :datetime
    t.column "updated_by",   :integer
    t.column "updated_at",   :datetime
  end

  create_table "punchout_sessions", :force => true do |t|
    t.column "user_id",          :integer
    t.column "punchout_site_id", :integer
    t.column "buyer_cookie",     :string
    t.column "seller_cookie",    :string
    t.column "created_by",       :integer
    t.column "created_at",       :datetime
    t.column "updated_by",       :integer
    t.column "updated_at",       :datetime
  end

  create_table "punchout_sites", :force => true do |t|
    t.column "name",            :string
    t.column "url",             :string
    t.column "description",     :string
    t.column "domain",          :string
    t.column "identity",        :string
    t.column "secret",          :string
    t.column "sender_domain",   :string
    t.column "sender_identity", :string
    t.column "protocol",        :string
    t.column "created_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_by",      :integer
    t.column "updated_at",      :datetime
    t.column "contract_id",     :integer
    t.column "lead_time",       :integer
  end

  create_table "receipts", :force => true do |t|
    t.column "receivable_id",   :integer
    t.column "receivable_type", :string
    t.column "receipt_date",    :datetime
    t.column "quantity",        :float
    t.column "unit_price",      :decimal,                 :precision => 30, :scale => 2
    t.column "created_by",      :integer
    t.column "updated_by",      :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "type",            :string,   :limit => 100
    t.column "total",           :decimal,                 :precision => 30, :scale => 2
    t.column "uom_id",          :integer
    t.column "currency_id",     :integer
  end

  create_table "requisition_event_history", :force => true do |t|
    t.column "created_by",            :integer
    t.column "updated_by",            :integer
    t.column "created_at",            :datetime
    t.column "updated_at",            :datetime
    t.column "requisition_header_id", :integer
    t.column "status",                :string,   :limit => 50
  end

  create_table "requisition_headers", :force => true do |t|
    t.column "status",             :string,   :limit => 50, :default => "", :null => false
    t.column "requested_by",       :integer
    t.column "need_by_date",       :datetime
    t.column "account_id",         :integer
    t.column "created_by",         :integer
    t.column "updated_by",         :integer
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "ship_to_address_id", :integer
    t.column "approval_id",        :integer
    t.column "justification",      :text
    t.column "deleted_at",         :datetime
    t.column "buyer_note",         :text
    t.column "pcard_id",           :integer
    t.column "reject_reason",      :text
    t.column "submitted_at",       :datetime
  end

  create_table "requisition_line_templates", :force => true do |t|
    t.column "name",                    :string,   :limit => 100
    t.column "form_id",                 :integer
    t.column "created_by",              :integer
    t.column "created_at",              :datetime
    t.column "updated_by",              :integer
    t.column "updated_at",              :integer
    t.column "line_type",               :string,   :limit => 100
    t.column "description",             :string
    t.column "quantity",                :float
    t.column "uom_id",                  :integer
    t.column "unit_price",              :decimal,                 :precision => 30, :scale => 2
    t.column "description_locked",      :boolean
    t.column "quantity_locked",         :boolean
    t.column "uom_locked",              :boolean
    t.column "unit_price_locked",       :boolean
    t.column "supplier_id",             :integer
    t.column "supplier_locked",         :boolean
    t.column "supplier_address_id",     :integer
    t.column "supplier_address_locked", :boolean
    t.column "contract_id",             :integer
    t.column "contract_locked",         :boolean
    t.column "status",                  :string,   :limit => 50
    t.column "lead_time",               :integer
  end

  create_table "requisition_lines", :force => true do |t|
    t.column "header_id",                    :integer,                                                :default => 0, :null => false
    t.column "line_num",                     :integer,                                                :default => 0, :null => false
    t.column "description",                  :string
    t.column "item_id",                      :integer
    t.column "quantity",                     :float
    t.column "uom_id",                       :integer
    t.column "unit_price",                   :decimal,                 :precision => 30, :scale => 2
    t.column "created_by",                   :integer
    t.column "updated_by",                   :integer
    t.column "created_at",                   :datetime
    t.column "updated_at",                   :datetime
    t.column "order_line_id",                :integer
    t.column "deleted_at",                   :datetime
    t.column "total",                        :decimal,                 :precision => 30, :scale => 2
    t.column "type",                         :string,   :limit => 100
    t.column "status",                       :string,   :limit => 50
    t.column "suggested_suppliers",          :string
    t.column "requisition_line_template_id", :integer
    t.column "supplier_id",                  :integer
    t.column "contract_id",                  :integer
    t.column "form_response_id",             :integer
    t.column "released_by_buyer",            :boolean
    t.column "source_part_num",              :string
    t.column "currency_id",                  :integer
    t.column "punchout_site_id",             :integer
    t.column "need_by_date",                 :datetime
  end

  create_table "roles", :force => true do |t|
    t.column "name",        :string,  :default => "",    :null => false
    t.column "description", :string
    t.column "omnipotent",  :boolean, :default => false, :null => false
    t.column "system_role", :boolean, :default => false, :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "setup", :force => true do |t|
    t.column "key",        :string,   :limit => 50
    t.column "value",      :string
    t.column "created_by", :integer
    t.column "created_at", :datetime
    t.column "updated_by", :integer
    t.column "updated_at", :datetime
  end

  create_table "shopping_cart_items", :force => true do |t|
    t.column "shopping_cart_id", :integer,  :default => 0,   :null => false
    t.column "item_id",          :integer,  :default => 0,   :null => false
    t.column "quantity",         :float,    :default => 0.0, :null => false
    t.column "created_by",       :integer
    t.column "updated_by",       :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "shopping_carts", :force => true do |t|
    t.column "user_id",    :integer,  :default => 0, :null => false
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "suppliers", :force => true do |t|
    t.column "name",                   :string,   :limit => 100, :default => "", :null => false
    t.column "corporate_url",          :string
    t.column "storefront_url",         :string
    t.column "created_by",             :integer
    t.column "updated_by",             :integer
    t.column "created_at",             :datetime
    t.column "updated_at",             :datetime
    t.column "parent_id",              :integer
    t.column "primary_contact_id",     :integer
    t.column "primary_address_id",     :integer
    t.column "status",                 :string,   :limit => 100
    t.column "invoice_matching_level", :string
    t.column "on_hold",                :boolean
    t.column "po_method",              :string
    t.column "cxml_url",               :string
    t.column "cxml_domain",            :string
    t.column "cxml_identity",          :string
    t.column "cxml_supplier_domain",   :string
    t.column "cxml_supplier_identity", :string
    t.column "cxml_secret",            :string
    t.column "cxml_protocol",          :string
    t.column "account_number",         :string
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string,   :limit => 50
    t.column "created_by",    :integer
    t.column "created_at",    :datetime
    t.column "is_private",    :boolean,                :default => false
  end

  create_table "tags", :force => true do |t|
    t.column "name",       :string,   :limit => 30, :default => "", :null => false
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "tags", ["name"], :name => "tags_name_index"

  create_table "tasks", :force => true do |t|
    t.column "project_id", :integer
    t.column "name",       :string,   :limit => 100
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "uoms", :force => true do |t|
    t.column "code",                :string,  :limit => 6,   :default => "", :null => false
    t.column "name",                :string,  :limit => 100, :default => "", :null => false
    t.column "allowable_precision", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",               :string,   :limit => 80, :default => "",    :null => false
    t.column "salted_password",     :string,   :limit => 40, :default => "",    :null => false
    t.column "email",               :string,   :limit => 60, :default => "",    :null => false
    t.column "firstname",           :string,   :limit => 40
    t.column "lastname",            :string,   :limit => 40
    t.column "salt",                :string,   :limit => 40, :default => "",    :null => false
    t.column "verified",            :boolean,                :default => false
    t.column "role",                :string,   :limit => 40
    t.column "security_token",      :string,   :limit => 40
    t.column "token_expiry",        :datetime
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "logged_in_at",        :datetime
    t.column "deleted",             :boolean,                :default => false
    t.column "delete_after",        :datetime
    t.column "approval_limit_id",   :integer
    t.column "manager_id",          :integer
    t.column "default_address_id",  :integer
    t.column "default_account_id",  :integer
    t.column "deleted_at",          :datetime
    t.column "default_currency_id", :integer
    t.column "pcard_id",            :integer
    t.column "phone_work",          :string
    t.column "phone_mobile",        :string
    t.column "status",              :string
  end

  create_table "users_roles", :id => false, :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "role_id", :integer, :default => 0, :null => false
  end

  create_table "widgets", :force => true do |t|
    t.column "form_id",     :integer
    t.column "type",        :string,   :limit => 50
    t.column "label",       :string,   :limit => 100
    t.column "parent_id",   :integer
    t.column "created_by",  :integer
    t.column "updated_by",  :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "position",    :integer
    t.column "value",       :text
    t.column "max_length",  :integer
    t.column "rows",        :integer
    t.column "cols",        :integer
    t.column "is_selected", :boolean
    t.column "date_value",  :datetime
    t.column "name",        :string,   :limit => 50
    t.column "hint",        :string,   :limit => 50
    t.column "is_required", :boolean
  end

end
